### ISSUE TITLE
Failed to get earning transcript scrapping

### ISSUE THREAD

**Issue by UtahJazz88** [pushpu77/IIMA#1]
Hi!
I found that when I was trying run earning transcript scrapping.ipnb, the output .txt document empty after running the crawler.
So I am thinking about there is a problem when trying to get article content from Seeking Alpha.（Since Seeking Alpha is not free, I even tried sending a POST request to the login page to get a session cookie, but failed to process as well. ）
Can you give me some suggestion so that I can get the earning transcript for my research ?

**Comment by pushpu77** [comment]
Add a limit while sending a POST request
